// flow-typed signature: 1053a5c2dc03beea71676d0b14267785
// flow-typed version: <<STUB>>/babel-polyfill_v^6.26.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-polyfill' {
  declare module.exports: any;
}
